### ISSUE TITLE
Error in search_utils

### ISSUE THREAD

**Issue by dfm** [andycasey/dropbear#1]
With the query `david, spergel`, I get this error:

```
Traceback (most recent call last):
  File "/Users/dforeman/research/projects/andycasey/dropbear/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/dforeman/research/projects/andycasey/dropbear/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "simple.py", line 30, in search
    async for suggestion in search_utils.suggest_authors(author_names):
  File "/Users/dforeman/research/projects/andycasey/dropbear/search_utils.py", line 326, in suggest_authors
    async for suggestion in collate_authors(
  File "/Users/dforeman/research/projects/andycasey/dropbear/search_utils.py", line 387, in collate_authors
    key = unique_name_descriptor(author)
  File "/Users/dforeman/research/projects/andycasey/dropbear/search_utils.py", line 45, in unique_name_descriptor
    parsed = parse_author_name(author_name)
  File "/Users/dforeman/research/projects/andycasey/dropbear/search_utils.py", line 67, in parse_author_name
    last_name, given_names, suffix = author_name.split(",")
ValueError: too many values to unpack (expected 3)
```

**Comment by andycasey** [comment]
Sorry: I can't reproduce this on my end. If `simple.py` has been modified, can you push/paste the full contents of that file?

**Comment by dfm** [comment]
Pushed. Running `python simple.py` and navigating to http://localhost:8080 should do it
